import turtle as t
size = 100
neco = size*(2**0.5)
t.shape("turtle")
t.forward(size)
t.left(135)
t.forward(neco)
t.right(135)
t.forward(size)
t.right(135)
t.forward(neco)
t.right(135)
t.forward(size)
t.right(45)
t.forward(neco/2)
t.right(90)
t.forward(neco/2)
t.right(45)
t.forward(size)
